#############################################################################
# Generated by PAGE version 4.20
#  in conjunction with Tcl version 8.6
#  Feb 27, 2019 07:43:57 PM IST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Eras Bold ITC} -size 15 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font10
vTcl:font:add_font \
    "-family {Comic Sans MS} -size 18 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font9
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m47" -background {#8a8b8c} -highlightbackground {#666666} \
        -highlightcolor {#6b6b6b} 
    wm focusmodel $top passive
    wm geometry $top 1366x705+1+-30
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1370 749
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm iconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Piction" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra43 \
        -borderwidth 2 -relief groove -background {#3a3630} -height 705 \
        -highlightbackground {#848484} -highlightcolor {#092e11} -width 255 
    vTcl:DefineAlias "$top.fra43" "feature_container" vTcl:WidgetProc "Piction" 1
    set site_3_0 $top.fra43
    ttk::label $site_3_0.tLa45 \
        -background {#3a3630} -foreground {#ffffff} \
        -font $::vTcl(fonts,vTcl:font9,object) -relief flat \
        -text {Start Editing} 
    vTcl:DefineAlias "$site_3_0.tLa45" "main_text" vTcl:WidgetProc "Piction" 1
    listbox $site_3_0.lis46 \
        -background {#3a3630} -disabledforeground {#a3a3a3} -font font17 \
        -foreground {#fcff9e} -height 572 -highlightbackground {#3a3630} \
        -highlightcolor black -selectbackground {#c4c4c4} \
        -selectforeground black -width 214 
    .top42.fra43.lis46 configure -font font17
    .top42.fra43.lis46 insert end text
    vTcl:DefineAlias "$site_3_0.lis46" "feature_list" vTcl:WidgetProc "Piction" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu48 \
        -takefocus {} -text Open 
    vTcl:DefineAlias "$site_3_0.tBu48" "open_button" vTcl:WidgetProc "Piction" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu49 \
        -takefocus {} -text Save 
    vTcl:DefineAlias "$site_3_0.tBu49" "save_button" vTcl:WidgetProc "Piction" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu51 \
        -takefocus {} -text Undo 
    vTcl:DefineAlias "$site_3_0.tBu51" "undo_button" vTcl:WidgetProc "Piction" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu52 \
        -takefocus {} -text Redo 
    vTcl:DefineAlias "$site_3_0.tBu52" "redo_button" vTcl:WidgetProc "Piction" 1
    place $site_3_0.tLa45 \
        -in $site_3_0 -x 10 -y 10 -width 236 -relwidth 0 -height 39 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lis46 \
        -in $site_3_0 -x 20 -y 50 -width 214 -relwidth 0 -height 572 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu48 \
        -in $site_3_0 -x 30 -y 670 -width 86 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu49 \
        -in $site_3_0 -x 140 -y 670 -width 86 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu51 \
        -in $site_3_0 -x 30 -y 630 -width 86 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tBu52 \
        -in $site_3_0 -x 140 -y 630 -width 86 -height 25 -anchor nw \
        -bordermode ignore 
    frame $top.fra44 \
        -borderwidth 2 -relief groove -background {#3a3630} -height 705 \
        -highlightbackground {#515151} -highlightcolor black -width 255 
    vTcl:DefineAlias "$top.fra44" "Frame1_1" vTcl:WidgetProc "Piction" 1
    set site_3_0 $top.fra44
    ttk::label $site_3_0.tLa43 \
        -background {#3a3630} -foreground {#ffffff} \
        -font $::vTcl(fonts,vTcl:font10,object) -relief flat -text Edit 
    vTcl:DefineAlias "$site_3_0.tLa43" "feature_name" vTcl:WidgetProc "Piction" 1
    text $site_3_0.tex44 \
        -background {#3a3630} -borderwidth 2 -cursor arrow -font font13 \
        -foreground {#ffffff} -height 194 -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -width 214 \
        -wrap word 
    .top42.fra44.tex44 configure -font font13
    .top42.fra44.tex44 insert end text
    vTcl:DefineAlias "$site_3_0.tex44" "description" vTcl:WidgetProc "Piction" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu45 \
        -takefocus {} -text Apply 
    vTcl:DefineAlias "$site_3_0.tBu45" "apply_button" vTcl:WidgetProc "Piction" 1
    ttk::label $site_3_0.tLa44 \
        -background {#3a3630} -foreground {#ffffff} -font TkDefaultFont \
        -relief flat -text Tlabel 
    vTcl:DefineAlias "$site_3_0.tLa44" "edit_label1" vTcl:WidgetProc "Piction" 1
    ttk::label $site_3_0.tLa45 \
        -background {#d9d9d9} -foreground {#000000} -font TkDefaultFont \
        -relief flat -text Tlabel 
    vTcl:DefineAlias "$site_3_0.tLa45" "TLabel1_1" vTcl:WidgetProc "Piction" 1
    entry $site_3_0.ent49 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent49" "edit_entry1" vTcl:WidgetProc "Piction" 1
    entry $site_3_0.ent50 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent50" "Entry1_4" vTcl:WidgetProc "Piction" 1
    place $site_3_0.tLa43 \
        -in $site_3_0 -x 20 -y 20 -width 216 -relwidth 0 -height 39 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tex44 \
        -in $site_3_0 -x 20 -y 60 -width 214 -relwidth 0 -height 194 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu45 \
        -in $site_3_0 -x 30 -y 650 -width 196 -relwidth 0 -height 35 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa44 \
        -in $site_3_0 -x 20 -y 280 -width 86 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa45 \
        -in $site_3_0 -x 948 -y 163 -width 96 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent49 \
        -in $site_3_0 -x 120 -y 280 -width 114 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent50 \
        -in $site_3_0 -x 681 -y 77 -width 114 -height 20 -anchor nw \
        -bordermode ignore 
    ttk::label $top.tLa46 \
        -background {#3a3630} -foreground {#ffffff} -font TkDefaultFont \
        -relief flat -text Tlabel 
    vTcl:DefineAlias "$top.tLa46" "edit_label2" vTcl:WidgetProc "Piction" 1
    set site_3_0 $top.m47
    menu $site_3_0 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    ttk::label $top.tLa48 \
        -background {#3a3630} -foreground {#ffffff} -font TkDefaultFont \
        -relief flat -text Tlabel 
    vTcl:DefineAlias "$top.tLa48" "edit_label3" vTcl:WidgetProc "Piction" 1
    entry $top.ent51 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent51" "edit_entry2" vTcl:WidgetProc "Piction" 1
    entry $top.ent52 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent52" "edit_entry3" vTcl:WidgetProc "Piction" 1
    entry $top.ent53 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent53" "Entry1_7" vTcl:WidgetProc "Piction" 1
    ttk::label $top.tLa54 \
        -background {#3a3630} -foreground {#ffffff} -font TkDefaultFont \
        -relief flat -text Tlabel 
    vTcl:DefineAlias "$top.tLa54" "edit_label4" vTcl:WidgetProc "Piction" 1
    ttk::label $top.tLa43 \
        -background {#3a3630} -foreground {#ffffff} -font TkDefaultFont \
        -relief flat -text Tlabel 
    vTcl:DefineAlias "$top.tLa43" "edit_label5" vTcl:WidgetProc "Piction" 1
    entry $top.ent44 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent44" "edit_entry5" vTcl:WidgetProc "Piction" 1
    canvas $top.can45 \
        -background {#d9d9d9} -borderwidth 2 -closeenough 1.0 -height 443 \
        -insertbackground black -relief ridge -selectbackground {#c4c4c4} \
        -selectforeground black -width 473 
    vTcl:DefineAlias "$top.can45" "image_area" vTcl:WidgetProc "Piction" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra43 \
        -in $top -x 0 -y 0 -width 255 -relwidth 0 -height 705 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra44 \
        -in $top -x 1110 -y 0 -width 255 -height 705 -anchor nw \
        -bordermode ignore 
    place $top.tLa46 \
        -in $top -x 1130 -y 320 -width 86 -relwidth 0 -height 19 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tLa48 \
        -in $top -x 1130 -y 360 -width 86 -relwidth 0 -height 19 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent51 \
        -in $top -x 1230 -y 320 -width 114 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent52 \
        -in $top -x 1230 -y 360 -width 114 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent53 \
        -in $top -x 1230 -y 400 -width 114 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.tLa54 \
        -in $top -x 1130 -y 400 -width 86 -height 19 -anchor nw \
        -bordermode ignore 
    place $top.tLa43 \
        -in $top -x 1130 -y 440 -width 86 -height 19 -anchor nw \
        -bordermode ignore 
    place $top.ent44 \
        -in $top -x 1230 -y 440 -width 114 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.can45 \
        -in $top -x 460 -y 130 -width 473 -relwidth 0 -height 443 \
        -relheight 0 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

